const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_EVENTS: 'GET_EVENTS',
    GET_ONE_EVENT: 'GET_ONE_EVENT',
    GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
    FETCH_SPEAKERS: 'FETCH_SPEAKERS',
    CREATE_SPEAKER: 'CREATE_SPEAKER',
    SET_SPEAKER_FORM_ERRORS: 'SET_SPEAKER_FORM_ERRORS',
}

export default ACTIONS