const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_EVENTS: 'GET_EVENTS',
    GET_ONE_EVENT: "GET_ONE_EVENT"
}

export default ACTIONS